name: DEPLOY

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy no EC2
        run: |
          echo "${{secrets.KEY_EC2}}" > private_key && chmod 400 private_key
             ssh -o StrictHostKeyChecking=no -i "private_key" ubuntu@ec2-54-160-140-119.compute-1.amazonaws.com "
                 cd /var/www/html/estudandoDevopsStatic &&
                 sudo git pull "
      - name: Publicar no RENDER
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.service_id }}
          api-key: ${{ secrets.api_key }}
